<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>bundleUUID</key>
        <string>3ea97d2e-6c70-4e35-b4d8-6ad4ae555d63</string>
        <key>comment</key>
        <string>
            nothing
        </string>
        <key>fileTypes</key>
        <array>
            <string>cf</string>
            <string>cf3</string>
        </array>
        <key>firstLineMatch</key>
        <string>^#!/.*\bcfengine[0-9.-]*\b</string>
        <key>foldingStartMarker</key>
        <string>^\s*(bundle)\s*([.a-zA-Z0-9_ &lt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
        <key>foldingStopMarker</key>
        <string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
        <key>keyEquivalent</key>
        <string>^~P</string>
        <key>name</key>
        <string>Cfengine3</string>
        <key>patterns</key>
        <array>
            <dict>
                <!-- bundle definition -->
                <key>begin</key>
                <string>^\s*(body|bundle)\s+([a-zA-Z0-9_]+)\s+([a-zA-Z0-9_]+)\s*</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.flow.cfengine</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>support.type.cfengine</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.cfengine</string>
                    </dict>
                </dict>

                <key>end</key>
                <string>\s*(\))?\s*\{?$</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.parameters.end.cfengine</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.function.cfengine</string>

                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(\()</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.parameters.begin.cfengine</string>
                            </dict>
                        </dict>
                        <key>contentName</key>
                        <string>meta.function.parameters.cfengine</string>
                        <key>end</key>
                        <string>(\)\s*)</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>captures</key>
                                <dict>
                                    <key>1</key>
                                    <dict>
                                        <key>name</key>
                                        <string>variable.parameter.function.cfengine</string>
                                    </dict>
                                    <key>2</key>
                                    <dict>
                                        <key>name</key>
                                        <string>punctuation.separator.parameters.cfengine</string>
                                    </dict>
                                </dict>
                                <key>match</key>
                                <string>\b([a-zA-Z_][a-zA-Z_0-9]*)\s*(?:(,)|(?=[\n\)]))</string>
                            </dict>
                        </array>
                    </dict>
                </array>

            </dict>

            <!-- promise type definition -->
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.promise.type.cfengine</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.promise.definition.cfengine</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^\s*([a-zA-Z0-9_]+)(:)\s*$</string>

                <key>name</key>
                <string>meta.promise.cfengine</string>
            </dict>

            <dict>
                <key>match</key>
                <string>^\s*([!a-zA-Z0-9_|&.()]+)::</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.other.inherited-class.name.cfengine</string>
                    </dict>
                </dict>
            </dict>
            
            <dict>
                <key>match</key>
                <string>([!])[!a-zA-Z0-9_|&.()]+::</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.class.negate.cfengine</string>
                    </dict>
                </dict>
            </dict>


            <!-- classes 
            <dict>
                <key>begin</key>
                <string>(^\s*)!?[a-zA-Z_]+</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.class.begin.cfengine</string>
                    </dict>
                </dict>
                <key>contentName</key>
                <string>meta.classes.cfengine</string>
                <key>end</key>
                <string>([^\s](::)\s*$)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>entity.other.inherited-class.name.cfengine</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.class.separator.cfengine</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>\b([a-zA-Z_][a-zA-Z_0-9]*)\s*(?:(\|)|(?=[::]))</string>
                    </dict>
                </array>
            </dict>
-->

            <!-- Comments -->
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>

            <dict>
                <key>include</key>
                <string>#string_quoted_double</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#string_quoted_single</string>
            </dict>


        </array>
        <key>repository</key>
        <dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.cfengine</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>(#).*?($\n?|(?=\?&gt;))</string>
                        <key>name</key>
                        <string>comment.line.number-sign.cfengine</string>
                    </dict>
                </array>
            </dict>

            <key>string_quoted_double</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(")</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.cfengine</string>
                            </dict>
                        </dict>
                        <key>comment</key>
                        <string>double quoted string</string>
                        <key>end</key>
                        <string>((?&lt;=")(")|")|(\n)</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.cfengine</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>meta.empty-string.double.cfengine</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>invalid.illegal.unclosed-string.cfengine</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.double.single-line.cfengine</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#escaped_char</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>

            <key>string_quoted_single</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(')</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.cfengine</string>
                            </dict>
                        </dict>
                        <key>comment</key>
                        <string>single quoted string</string>
                        <key>end</key>
                        <string>(')|(\n)</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.cfengine</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>invalid.illegal.unclosed-string.cfengine</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.single.single-line.cfengine</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#escaped_char</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>

            <key>escaped_char</key>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.hex.cfengine</string>
                    </dict>
                    <key>10</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.linefeed.cfengine</string>
                    </dict>
                    <key>11</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.return.cfengine</string>
                    </dict>
                    <key>12</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.tab.cfengine</string>
                    </dict>
                    <key>13</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.vertical-tab.cfengine</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.octal.cfengine</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.newline.cfengine</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.backlash.cfengine</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.double-quote.cfengine</string>
                    </dict>
                    <key>6</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.single-quote.cfengine</string>
                    </dict>
                    <key>7</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.bell.cfengine</string>
                    </dict>
                    <key>8</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.backspace.cfengine</string>
                    </dict>
                    <key>9</key>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.formfeed.cfengine</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\\x[0-9A-F]{2})|(\\[0-7]{3})|(\\\n)|(\\\\)|(\\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
            </dict>

            <key>promise_type_common</key>
            <dict>
                <key>match</key>
                <string>\b(meta|vars|defaults|classes|reports)\b</string>
                <key>name</key>
                <string>support.promise.type.common.cfengine</string>
            </dict>

            <key>promise_type_agent</key>
            <dict>
                <key>match</key>
                <string>\b(files|packages|guest_environments|methods|processes|services|commands|storage|databases)\b</string>
                <key>name</key>
                <string>support.promise.type.agent.cfengine</string>
            </dict>

        </dict>
        <key>scopeName</key>
        <string>source.cfengine</string>
        <key>uuid</key>
        <string>3ea97d2e-6c70-4e35-b4d8-6ad4ae555d63</string>
    </dict>
</plist>
